"""add eventticket columns to workshop db

Revision ID: 11b7a0080944
Revises: cdd83c2c76b1
Create Date: 2024-04-26 20:45:52.608430

"""

# revision identifiers, used by Alembic.
revision = '11b7a0080944'
down_revision = 'cdd83c2c76b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('requires_ticket', sa.Boolean(), nullable=False))
    op.add_column('proposal', sa.Column('non_lottery_tickts', sa.Integer(), nullable=True))
    op.add_column('proposal_version', sa.Column('requires_ticket', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('proposal_version', sa.Column('non_lottery_tickts', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal_version', 'non_lottery_tickts')
    op.drop_column('proposal_version', 'requires_ticket')
    op.drop_column('proposal', 'non_lottery_tickts')
    op.drop_column('proposal', 'requires_ticket')
    # ### end Alembic commands ###
