"""add EventTicket table

Revision ID: cdd83c2c76b1
Revises: 7a6816e652f2
Create Date: 2024-04-21 22:02:49.807983

"""

# revision identifiers, used by Alembic.
revision = 'cdd83c2c76b1'
down_revision = '7a6816e652f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['proposal.id'], name=op.f('fk_event_ticket_event_id_proposal')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_event_ticket_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_ticket'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_ticket')
    # ### end Alembic commands ###
